on:
  push:
    branches:
      - "deploy"

jobs:
  deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          dist s3://issue-tracker-github-action-test
