name: "Build & Deploy"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: '${{ secrets.AWS_BUCKET_NAME }}'
          AWS_REGION: '${{ secrets.AWS_BUCKET_REGION }}'
          ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          SOURCE_DIR: "build"

